name: Upload Python Package

on:
  push:
    branches:
      - main
    paths:
      - PYTHON_PKG/std/pyproject.toml

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: build release distributions
        run: |
          # NOTE: put your own distribution build steps here.
          cd PYTHON_PKG/std
          # open pyproject.toml and delete all optional dependencies
          python -c """
          import toml
          with open('pyproject.toml', 'r') as f:
              data = toml.load(f)
              
          # Filter out optional dependencies containing 'git'
          if 'project' in data and 'optional-dependencies' in data['project']:
              filtered_deps = {
                  key: value for key, value in data['project']['optional-dependencies'].items()
                  if not any('git' in str(dep) for dep in value)
              }
              data['project']['optional-dependencies'] = filtered_deps

          with open('pyproject.toml', 'w') as f:
              toml.dump(data, f)
          """
          python -m pip install build
          python -m build
      - name: upload windows dists
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: PYTHON_PKG/std/dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: PYTHON_PKG/std/dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1